[mypy]
python_version = 3.12
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin

[mypy.plugins.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[mypy-asyncpg.*]
ignore_missing_imports = true

[mypy-redis.*]
ignore_missing_imports = true
