{{- if .Values.taskEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: task-engine
  labels:
    {{- include "kutana.labels" . | nindent 4 }}
    app.kubernetes.io/name: task-engine
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: task-engine
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
